services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user_management_db
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev-seed,filelog
      - JWT_SECRET=${JWT_SECRET}